### ISSUE TITLE
Create a CS1 example LearningMaterials file

### ISSUE THREAD

**Issue by phernandoe** [tobydragon/ConceptKnowledgeCalculator#411]

**Comment by phernandoe** [comment]
Wrote file, tested output and modified existing tests to account for the added file. Also modified wiki for default tags
Time taken: 30 minutes.

**Comment by tobydragon** [comment]
should be a josn file, text files should not be integrated with larger project yet.

**Comment by phernandoe** [comment]
Created json file containing 6 Cs1 learning materials with tags
Time taken: 30 minutes
