### ISSUE TITLE
make data Importance available in javascript and make sure all estimates are 0-1

### ISSUE THREAD

**Issue by wsuchanek** [tobydragon/ConceptKnowledgeCalculator#51]
Currently it goes from -1 to 1 and the issue is if you are using information from a gradebook you will never hit anything below 0.

Done:
Either 
1. change the scale from "-1 to 1" to "0 to 1"

2. change the calculation to normalize scores from 0 to 2 then subtract 1 from the score to end up back on the -1 to 1 scale

**Comment by tobydragon** [comment]
narrative: visualize

**Comment by tobydragon** [comment]
data importance is not normalized, will need to do something about this... see #139

**Comment by tobydragon** [comment]
#139

**Comment by tobydragon** [comment]
1 hr
