### ISSUE TITLE
using R functions within java code

### ISSUE THREAD

**Issue by tobydragon** [tobydragon/ConceptKnowledgeCalculator#54]
Done when: 
- an R function can be run and return results to java code. 
- demonstrates the manner in which complex data structures are shared do we share through matrices?)

**Comment by tobydragon** [comment]
Promising-looking software solution:
https://github.com/jbytecode/rcaller

To install this, use import library from maven in IntelliJ

**Comment by benleblanket** [comment]
8hrs - Researching and testing integration of R within Java. Small set up for testing transfer of files from java to R script. .R files can be created and written inside java but not run at the moment.

**Comment by tobydragon** [comment]
Did you try the software RCaller linked above? It even has a publication that gives example code (https://github.com/jbytecode/rcaller/blob/master/doc/rcaller3/rcaller3.pdf).  If this is not successful, can you list what you tried and why it failed as comments, so others don't repeat the same work?

Also, if this doesn't work, the paper mentions two other possibilities, rJava and rServe. They seem relatively more complicated to set up, but also viable options.

**Comment by benleblanket** [comment]
I have tried RCaller. I believe it could work. My main problem is that I cannot set up certain pieces correctly and everything I have tried either simply does not work or the R script gives an Access Denied error or asks me to install an R interpreter whenever it attempts to run, which based on looking online sounds like it is just the R program itself without any IDE but the information on it is so slim I cannot tell. Either way, pathing the interpreter to multiple versions of R is not fixing the error.

Today I can look into other options such as rServe and also continue to fix the errors I am getting, but again, I do not think this is a problem with the Java/intelliJ side of things. It is more of a problem with the R side of things and something I am missing in hooking it up correctly.

**Comment by benleblanket** [comment]
4 hrs - looking into usage for RCaller
8hrs - computer setup; learning RCaller commands; writing a simple function.
Having trouble using/returning doubles. RCaller commands work a lot with arrays.

**Comment by benleblanket** [comment]
8hrs - Mac setup with RCaller (code that works whether running on Mac or Windows), wiki page on R integration setup created, matrices testing

**Comment by benleblanket** [comment]
(Fri/Sat) 8hrs - Working with .csv example data, looking at pieces of the project's code, coming up with questions for Matt.
8hrs - Finishing up making .csv example tests, looking into the project files (specifically CSVReader and CSVOutputter), and preparing for a sprint goal
