### ISSUE TITLE
Javadoc comments for suggester and others

### ISSUE THREAD

**Issue by tobydragon** [tobydragon/ConceptKnowledgeCalculator#61]
see todo list where javadoc comments are requested. Currently in ConceptGraph, ConceptNode, and suggester. Moving forward, we should try to write them along with the testing code so that they are always defined for our new functions

**Comment by ekimmichmitchell** [comment]
Completed javadocs for functions in ConceptNode 

-complete conceptGraph and suggester when finish functions: buildSuggestionMap() and ancestry()

**Comment by ekimmichmitchell** [comment]
45 mins
