### ISSUE TITLE
Fix ancestry function at Graph level

### ISSUE THREAD

**Issue by tobydragon** [tobydragon/ConceptKnowledgeCalculator#62]
the ancestry function does not seem to perform the task we need at the graph level (although the one at the node level seems good). It seems this would exclude a suggestion of anything that is not a leaf node… 

We really want to exclude only nodes that are ancestors of nodes that are already included in the suggestion list. Similarly, when we want to suggest a descendant, I guess we would want to remove any ancestors of that node from the suggestion list before adding the descendant to the list. This seems complicated and like it needs good examples, but I think the way it is working now is not the goal...

Done when: there are clear working examples of how the ancestry function should work, written as tests in the ConceptGraphTest class and a javadoc comment on the ancsestry function clarifying the exact purpose it serves.

**Comment by ekimmichmitchell** [comment]
2 hours 
changed parameters to be the list and the current node it's checking.

**Comment by ekimmichmitchell** [comment]
1.5 hr creating acnestryTest and creating Example ConceptGraphFactory.mediumStructure for testing. 
junit not working
