### ISSUE TITLE
clean out test resources folder

### ISSUE THREAD

**Issue by tobydragon** [tobydragon/ConceptKnowledgeCalculator#66]
Find which resource json files are actually being used, delete all others. See if each that is being used is actually useful and different than others. Come up with a naming convention scheme and rename them in a meaningful way. Separate files that are written by the system during tests from ones that have been written by hand, keep them in separate directories, put the written by system directory in gitignore so that each tester is writing their own files.

**Comment by tobydragon** [comment]
Another task here is to make the data input format match precisely with the latest practical example, which can be found in resources/comp220.  For example, there are not initial values for estimates or labels in the data...

**Comment by ekimmichmitchell** [comment]
3.5 hours

**Comment by ekimmichmitchell** [comment]
changing input format not done
