### ISSUE TITLE
Add suggestion request functionality to the API

### ISSUE THREAD

**Issue by tobydragon** [tobydragon/ConceptKnowledgeCalculator#71]
Done when: There are API functions that offer the following returns:
  - concept suggestions for a student
  - learning object suggestions for a student
  - learning object suggestions for a given student and concept
 (this will require changing the API as well, since there are only two functions now and they might be named as best they could).

**Comment by ekimmichmitchell** [comment]
2 hours

**Comment by ekimmichmitchell** [comment]
2
