### ISSUE TITLE
Add suggeting functionality to the console

### ISSUE THREAD

**Issue by tobydragon** [tobydragon/ConceptKnowledgeCalculator#72]
After completing #71, the functionality for suggestions should be made accessible through the console UI. This means they must have menu options to request the different kinds of suggestions, and the console class can parse the returned data structures and display them in plain, readable text.

Done when:  a user can look at a graph and make suggestion requests though the console window. Results are displayed in a readable manner.

**Comment by ekimmichmitchell** [comment]
2 hours
