### ISSUE TITLE
Automate process of creating resources file

### ISSUE THREAD

**Issue by tobydragon** [tobydragon/ConceptKnowledgeCalculator#75]
The skeleton for the json file for resources can be created automatically by pulling the resource ids from a csv file, creating a LOLinks object with all empty lists, and writing that file out to console. 
 
It should also include a list (bottom or top) of all current concept ids, that will need to be deleted but can be used for memory and to copy / paste  into id slots in created list json

**Comment by ekimmichmitchell** [comment]
see #48

**Comment by benleblanket** [comment]
5hr - individual functions needed for task are made. still have to connect things together and further test

**Comment by benleblanket** [comment]
7hr

**Comment by benleblanket** [comment]
2.5hr

**Comment by benleblanket** [comment]
2hr
