### ISSUE TITLE
CSVReader can't handle commas in names of assignments

### ISSUE THREAD

**Issue by tobydragon** [tobydragon/ConceptKnowledgeCalculator#77]
Sakai handles this by wrapping those in quotes, for example:
Day 02 Reading - C++ Intro [6],"Day 06 Reading - Pointers, Arrays, and Dynamic Memory [6]",Day 09 Reading - Ponters and const [2],

Done when:  And assingment name scan be surrounded with quotes and have commas in it an still be pared correctly by system

**Comment by rDeBolt** [comment]
Created an algorithm to separate  lines by commas correctly , created tests to check the effectiveness of the algorithm. (3 hours)
