### ISSUE TITLE
cohort ConceptGraph knowledge estimate problem

### ISSUE THREAD

**Issue by ekimmichmitchell** [tobydragon/ConceptKnowledgeCalculator#78]
The knowledge estimates seem to give wrong values when loaded.
done when: knowledge estimates are correct values (look at conceptGrahTest)

**Comment by ekimmichmitchell** [comment]
Classes to look at:
-wilExampleCohortGraphWithKnowledgeEstimates in PraticalConceptGraphTest
-calcKnowledgeEstimateTest in ConceptGraphTest

**Comment by tobydragon** [comment]
Found potential root of problem: the knowledgeEstimates are not equal, see CohortconcpetGraphsTest.calcKnowledgeEstimateSameInCohortAndConceptGraphsTest() for example

1 hr

**Comment by tobydragon** [comment]
Fixed: by finding a situation where copied graphs were making multiple copies of LearningObjects in ConceptNode copy constructor

2 hrs
