### ISSUE TITLE
Matrix of LearningObject responses

### ISSUE THREAD

**Issue by benleblanket** [tobydragon/ConceptKnowledgeCalculator#83]
Done when: A matrix of LearningObject x Student = LearningObjectResonse can be created

**Comment by benleblanket** [comment]
3hr - Looking into what is needed to be done in order to create this structure and beginning coding
8hr -  Collecting the LearningObjects and setting size of matrix. Still needs to structure the responses in with correct column and matching with the userID across entire row

**Comment by tobydragon** [comment]
Toby - 1 hr

**Comment by benleblanket** [comment]
8hr - Finishing up the code , testing and debugging
1hr - Test successful and cleaning up code
